name: Gradle Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        java-package: 'jdk'

    - name: Set up Gradle
      uses: gradle/wrapper-validation-action@v1

    - name: Build project
      run: ./gradlew build
