name: main

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml
    needs:
      - build

  pages:
    uses: ./.github/workflows/dokka.yml
    needs:
      - build
      - test
    if: github.ref == 'refs/heads/main'
